apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: FILLED_IN_BY_CI
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml