apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  annotations:
    fluxcd.io/automated: "true"
  labels:
    sandboxId: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  chart:
    git: https://github.com/biomage-org/pipeline
    path: chart-infra/
    ref: FILLED_IN_BY_CI
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml
