{
  "R": {
    "Version": "4.0.5",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.12/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.12/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.12/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.12/workflows"
      },
      {
        "Name": "BioCbooks",
        "URL": "https://bioconductor.org/packages/3.12/books"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Bioconductor": {
    "Version": "3.12"
  },
  "Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.75.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e4c04affc2cac20c8fec18385cd14691"
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.50.0",
      "Source": "Bioconductor",
      "Hash": "f49586e579b712b7e55253aba0c9bc21"
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.36.1",
      "Source": "Bioconductor",
      "Hash": "f628c51eadc74ffd838b801cd22d589a"
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.16",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2fdca0877debdd4668190832cdee4c31"
    },
    "BiocNeighbors": {
      "Package": "BiocNeighbors",
      "Version": "1.8.2",
      "Source": "Bioconductor",
      "Hash": "8a3634be325ede4f00afa7587eac479a"
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.24.1",
      "Source": "Bioconductor",
      "Hash": "338a72852f019b3b51ae87dc82391eb3"
    },
    "BiocSingular": {
      "Package": "BiocSingular",
      "Version": "1.6.0",
      "Source": "Bioconductor",
      "Hash": "b7d1aa70f71252a7f9d3a927d43846cd"
    },
    "ClusterR": {
      "Package": "ClusterR",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6d5265d95f326bb0cfd7274eeab8760c"
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.16.3",
      "Source": "Bioconductor",
      "Hash": "a87d32010153cba996c97fe2a52403e6"
    },
    "DelayedMatrixStats": {
      "Package": "DelayedMatrixStats",
      "Version": "1.12.3",
      "Source": "Bioconductor",
      "Hash": "1a9c016231c53483de05bec235ff8bfd"
    },
    "DropletUtils": {
      "Package": "DropletUtils",
      "Version": "1.10.3",
      "Source": "Bioconductor",
      "Hash": "f3e78fee6ebbdbfdf679cfeaa0ec0083"
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b56998fff55e4a4b4860ad6e8c67e0f9"
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.26.7",
      "Source": "Bioconductor",
      "Hash": "b8b4dfceea20ddae8893aa4ccb242dea"
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.4",
      "Source": "Bioconductor",
      "Hash": "8e9c39ceac5f1d98d3267541853fca31"
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.42.0",
      "Source": "Bioconductor",
      "Hash": "2826edf1a5ff7d6ce991ec5ed918ec5f"
    },
    "HDF5Array": {
      "Package": "HDF5Array",
      "Version": "1.18.1",
      "Source": "Bioconductor",
      "Hash": "07fd74c160b1265137c0cdd815dc42b5"
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.24.1",
      "Source": "Bioconductor",
      "Hash": "21b3bc3dfb55cb9501c5f3413b35388c"
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9e703ad8bf0e99f3691f05da32dfe68b"
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-53.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ef21dd0348b9abb7f8bd1d77e4cd0c3"
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.3-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ff280503079ad8623d3c4b1519b24ea2"
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.2.1",
      "Source": "Bioconductor",
      "Hash": "fbae799fc848a8599a46a3adfe8a975a"
    },
    "R.methodsS3": {
      "Package": "R.methodsS3",
      "Version": "1.8.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4bf6453323755202d5909697b6f7c109"
    },
    "R.oo": {
      "Package": "R.oo",
      "Version": "1.24.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5709328352717e2f0a9c012be8a97554"
    },
    "R.utils": {
      "Package": "R.utils",
      "Version": "2.10.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a9e316277ff12a43997266f2f6567780"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b203113193e70978a696b2809525649d"
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7"
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e031418365a7f7a766181ab5a41a5716"
    },
    "RCurl": {
      "Package": "RCurl",
      "Version": "1.98-1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ddac9abbfba243f9aeab9b5680b968d3"
    },
    "RJSONIO": {
      "Package": "RJSONIO",
      "Version": "1.3-1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5465553c5320701393a2daaa42ed58f9"
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cc151930e20e16427bc3d0daec62b4a9"
    },
    "RSpectra": {
      "Package": "RSpectra",
      "Version": "0.16-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a41329d24d5a98eaed2bd0159adb1b5f"
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dbb5e436998a7eba5a9d682060533338"
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4c61a26f751659e875f46045df6d5fad"
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.10.2.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a2de53472129933a29975e7cfa3ffe28"
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.3.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ddfa72a87fdf4c80466a20818be91d00"
    },
    "RcppHNSW": {
      "Package": "RcppHNSW",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ce584c040a9cfa786ffb41f938f5ed19"
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5"
    },
    "Rhdf5lib": {
      "Package": "Rhdf5lib",
      "Version": "1.12.1",
      "Source": "Bioconductor",
      "Hash": "7dc9be3558a910226d64a2040520dc7f"
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f153432c4ca15b937ccfaa40f167c892"
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.28.1",
      "Source": "Bioconductor",
      "Hash": "f558c55a285751bd72af11d2bb853521"
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "4.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9daeb378fb2819f01425b155b90f083d"
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "4.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0ac490e6dfe2e9f853b977ab9f101054"
    },
    "SeuratWrappers": {
      "Package": "SeuratWrappers",
      "Version": "0.3.0",
      "Source": "GitHub",
      "Remotes": "MacoskoLab/liger, hms-dbmi/conos, immunogenomics/harmony,\nimmunogenomics/presto, satijalab/seurat-data,\nvelocyto-team/velocyto.R, SaskiaFreytag/schex@031320d,\ncole-trapnell-lab/monocle3, mojaveazure/seurat-disk,\npowellgenomicslab/Nebulosa",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "seurat-wrappers",
      "RemoteUsername": "satijalab",
      "RemoteRef": "HEAD",
      "RemoteSha": "156e3925eec2a9180d76602d09b09a3eafb738e8",
      "Hash": "70fee03c828d4b3b272a6db808ccdf45"
    },
    "SingleCellExperiment": {
      "Package": "SingleCellExperiment",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Hash": "40badd4c5dcff81480c77a17b3b811bb"
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Hash": "2da24c5f66521d18cff602d324834b20"
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.30.0",
      "Source": "Bioconductor",
      "Hash": "9bd9f991fb4ecde6adeff2fa2e401cc5"
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862"
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e8a22846fff485f0be3770c2da758713"
    },
    "assertthat": {
      "Package": "assertthat",
      "Version": "0.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "50c838a310445e954bc13f26f26a6ecf"
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "543776ae6848fde2f48ff3816d0628bc"
    },
    "beachmat": {
      "Package": "beachmat",
      "Version": "2.6.4",
      "Source": "Bioconductor",
      "Hash": "8af9f5ade6bca275eb2c7cf22267032f"
    },
    "beeswarm": {
      "Package": "beeswarm",
      "Version": "0.2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dc538ec663e38888807ef3034489403d"
    },
    "benchmarkme": {
      "Package": "benchmarkme",
      "Version": "1.0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9213add5a4904660aeaf207bb62e515e"
    },
    "benchmarkmeData": {
      "Package": "benchmarkmeData",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "03127f8e60281ab3c52f96bb98056dcb"
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0b118d5900596bae6c4d4865374536a6"
    },
    "bluster": {
      "Package": "bluster",
      "Version": "1.0.0",
      "Source": "Bioconductor",
      "Hash": "e8f8b977ef40b50bdc3910453f9b48fd"
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.1.9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "brio",
      "RemoteUsername": "r-lib",
      "RemoteRef": "HEAD",
      "RemoteSha": "2cf72bb77ad55c758b4a140112916ddc23f00b59",
      "Hash": "37e48c0486e03e4f2799321aaa1fab58"
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4830a372b241d78ed6f53731ee3023ac"
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f5b3e8f693522708cd9444c839b432e0"
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2703a46dcabfb902f10060b2bca9f708"
    },
    "callr": {
      "Package": "callr",
      "Version": "3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d7f1e926dfcd57c74ce93f5c048e80"
    },
    "cli": {
      "Package": "cli",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a94ba44cee3ea571e813721e64184172"
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5ea8f54741ff907e2c0b5efabc9de729"
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "019388fc48e48b3da0d3a76ff94608a8"
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "abea3384649ef37f60ef51ce002f3547"
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f22be39ec1d141fd03683c06f3a6e67"
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b418e8423699d11c7f2087c2bfd07da2"
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.2.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8b9a10255e862eb99e38fa8b0caa6c0d"
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.4.1.9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "crayon",
      "RemoteUsername": "r-lib",
      "RemoteRef": "HEAD",
      "RemoteSha": "965d1dc161ae09b622145266807c7c9ab2ae925b",
      "Hash": "da54f2344a01fb3008c93e172f92d513"
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2b06f9e415a62b6762e4b8098d2aecbc"
    },
    "curl": {
      "Package": "curl",
      "Version": "4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2b7d10581cc730804e9ed178c8374bd6"
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.13.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "813fa8857aaa949b243e2e0b4abb8592"
    },
    "deldir": {
      "Package": "deldir",
      "Version": "0.2-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5ecce9536aef446cf9b7b8519c0effae"
    },
    "desc": {
      "Package": "desc",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6c8fe8fa26a23b79949375d372c7b395"
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "55fae7ec1418d2a47bd552571673d1af"
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a0cbe758a531d054b537d16dff4d58a1"
    },
    "doParallel": {
      "Package": "doParallel",
      "Version": "1.0.16",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2dc413572eb42475179bfe0afabd2adf"
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "365f8c3650ab95582e600f160fd5fb88"
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cc0d03e8383d407e9568855f8efbc07d"
    },
    "edgeR": {
      "Package": "edgeR",
      "Version": "3.32.1",
      "Source": "Bioconductor",
      "Hash": "9728a55a7f19cfab9c54d84b4e59f143"
    },
    "ellipsis": {
      "Package": "ellipsis",
      "Version": "0.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fd2844b3a43ae2d27e70ece2df1b4e2a"
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ec8ca05cffcc70569eaaad8469d2a3a7"
    },
    "fansi": {
      "Package": "fansi",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fea074fb67fe4c25d47ad09087da847d"
    },
    "farver": {
      "Package": "farver",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dad6793a5a1f73c8e91f1a1e3e834b05"
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77bd60a6157420d4ffa93b27cf6a58b8"
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8e9ca89621f9304a553e0ff119328053"
    },
    "foreach": {
      "Package": "foreach",
      "Version": "1.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e32cfc0973caba11b65b1fa691b4d8c9"
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ad36e26eeeb7393886d8a0e19bc6ee42"
    },
    "fs": {
      "Package": "fs",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "44594a07a42e5f91fac9f93fda6d0109"
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e"
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b"
    },
    "future": {
      "Package": "future",
      "Version": "1.21.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f25fad6bee82b7ab01f055e2d813b96f"
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7fb0dc1961807da107ab2078366052bd"
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4d243a9c10b00589889fe32314ffd902"
    },
    "ggbeeswarm": {
      "Package": "ggbeeswarm",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dd68b9b215b2d3119603549a794003c3"
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3eb6477d01eb5bbdc03f7d5f70f2733e"
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "08ab869f37e6a7741a64ab9069bcb67d"
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9d028e8f37c84dba356ce3c367a1978e"
    },
    "globals": {
      "Package": "globals",
      "Version": "0.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "eca8023ed5ca6372479ebb9b3207f5ae"
    },
    "glue": {
      "Package": "glue",
      "Version": "1.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6efd734b14c6471cfe443345f3e35e29"
    },
    "gmp": {
      "Package": "gmp",
      "Version": "0.6-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1811d8b0cd5baa7b55aafce65a037b69"
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3c9209bce1b10900155ea37ce954cf30"
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e65e5d5dea4cbb9ba822dcd782b2ee1f"
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7d7f283939f563670a697165b2cf5560"
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ac5c6baf7822ce8732b343f14c072c4d"
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.8.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0a749b4458d19a54acae93c64e3e7c85"
    },
    "harmony": {
      "Package": "harmony",
      "Version": "1.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "harmony",
      "RemoteUsername": "immunogenomics",
      "RemoteRef": "HEAD",
      "RemoteSha": "c8f4901ef92d6e9b4e1373c52de3b67ff052db3e",
      "Hash": "fea155423dc3c3cbfc95b7d44ed35cdf"
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "af2c2531e55df5cf230c4b5444fc973c"
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6fdaa86d0700f8b3e92ee3c445a5a10d"
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.5.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b9d5d39be2150cf86538b8488334b8f8"
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a525aba14184fec243f9eaec62fbed43"
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ba9b882bb834ecbdad37338a11f3f8"
    },
    "ids": {
      "Package": "ids",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "99df65cfef20e525ed38c3d2577f7190"
    },
    "igraph": {
      "Package": "igraph",
      "Version": "1.2.6.9112",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "rigraph",
      "RemoteUsername": "igraph",
      "RemoteRef": "master",
      "RemoteSha": "47f29e055fcc038d1d01af375295029f562969f3",
      "Hash": "00342c64f180563f21fa5339835c139c"
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a9ad517358000d57022401ef18ee657a"
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "53647fb507373700028b2ce6cd30751a"
    },
    "iterators": {
      "Package": "iterators",
      "Version": "1.0.13",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "64778782a89480e9a644f69aad9a2877"
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5ff50b36f7f0832f8421745af333e73c"
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "98138e0994d41508c7a6b84a0600cfcb"
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3d5108641f47470611a32d0bdf357a72"
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad"
    },
    "later": {
      "Package": "later",
      "Version": "1.1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d0a62b247165aabf397fded504660d8a"
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.20-41",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fbd9285028b0263d76d18c95ae51a53d"
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370"
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1682f03d884f71a47aad8a9527d79b74"
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3471fb65971f1a7b2d4ae7848cf2db8d"
    },
    "limma": {
      "Package": "limma",
      "Version": "3.46.0",
      "Source": "Bioconductor",
      "Hash": "78b860aa595c42e02464243a213b3e6d"
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.8.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0bde42ee282efb18c7c4e63822f5b4f7"
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-38",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b0edacc02f7a3dad41a1afc385e929f4"
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "760b5b542e8435237d1b3c253bfe18e7"
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "41287f1ac7d28a92f0a286ed507928d3"
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "0.58.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c318d148056e5bb8d7de79b0876f9ae6"
    },
    "mbkmeans": {
      "Package": "mbkmeans",
      "Version": "1.6.1",
      "Source": "Bioconductor",
      "Hash": "53174c4909070f048e27d55162074d6c"
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.8-34",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bd4a6c4b600f58651d60d381b0e9a397"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "26fa77e707223e1ce042b2b5d09993dc"
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fec5f52652d60615fdb3957b3d74324a"
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6dfe8bf774944bd5595785e3229d8771"
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-151",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "42c8ba2b6a32a6bf0874e93e3bd86a43"
    },
    "openssl": {
      "Package": "openssl",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a399e4773075fc2375b71f45fca186c4"
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.23.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2f841d7915986a8fd995ab4ec105dd1b"
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c446b30cb33ec125ff02588b60660ccb"
    },
    "paws": {
      "Package": "paws",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cec12e707388b40a0109c6e89b866176"
    },
    "paws.analytics": {
      "Package": "paws.analytics",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b27a7fab001c13d69cce406315f991c1"
    },
    "paws.application.integration": {
      "Package": "paws.application.integration",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "15be816c36116393eff157fe061cb564"
    },
    "paws.common": {
      "Package": "paws.common",
      "Version": "0.3.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "38cceefa81f793ca194e90f28c0bf804"
    },
    "paws.compute": {
      "Package": "paws.compute",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "421a8a6138b5707842d49c6b47cf48d8"
    },
    "paws.cost.management": {
      "Package": "paws.cost.management",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "37d8fd15437c3e41cbeaa826860b1452"
    },
    "paws.customer.engagement": {
      "Package": "paws.customer.engagement",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b2f091502ec3a74caba2628bfbc5aba1"
    },
    "paws.database": {
      "Package": "paws.database",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "27c9d75627046976c89f4a43279b5078"
    },
    "paws.machine.learning": {
      "Package": "paws.machine.learning",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "27fbc04572e5a74200c75ebf7a1ca5b3"
    },
    "paws.management": {
      "Package": "paws.management",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "85b61065160322f6729269cb59bd434e"
    },
    "paws.networking": {
      "Package": "paws.networking",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "603472424ac4c5244abba09728bd15e5"
    },
    "paws.security.identity": {
      "Package": "paws.security.identity",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d4d9f0ac7e665888c12d799421fcf345"
    },
    "paws.storage": {
      "Package": "paws.storage",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d0a0428696cdc8099e8c93d2257b21f2"
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "52f8028b028076bc3b7ee5d6251abf0d"
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3b3dd89b2ee115a8b54e93a34cd546b4"
    },
    "pkgbuild": {
      "Package": "pkgbuild",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "725fcc30222d4d11ec68efb8ff11a9af"
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "01f28d4278f15c76cddbea05899c5d6f"
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b6b150cd4709e0c0c9b5d51ac4376282"
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.9.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f6b85d9e4ed88074ea0ede1aa74bb00e"
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ec0e5ab4e5f851f6ef32cd1d1984957f"
    },
    "png": {
      "Package": "png",
      "Version": "0.1-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "03b7076c234cb3331288919983326c55"
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cb167f328b3ada4ec5cf67a7df4c900a"
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f"
    },
    "prettyunits": {
      "Package": "prettyunits",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ef9167b75dde9d2ccc3c7528393e7e"
    },
    "processx": {
      "Package": "processx",
      "Version": "3.4.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "22aab6098cb14edd0a5973a8438b569b"
    },
    "promises": {
      "Package": "promises",
      "Version": "1.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ab2c43adb4d4699cf3690acd378d75d"
    },
    "ps": {
      "Package": "ps",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ebaed51a03411fd5cfc1e12d9079b353"
    },
    "purrr": {
      "Package": "purrr",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "97def703420c8ab10d8f0e6c72101e02"
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d"
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "76c9e04c712a05848ae7a23d2f170a40"
    },
    "remotes": {
      "Package": "remotes",
      "Version": "2.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "430a0908aee75b1fcba0e62857cab0ce"
    },
    "renv": {
      "Package": "renv",
      "Version": "0.13.2",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "renv",
      "RemoteUsername": "rstudio",
      "RemoteRef": "0.13.2",
      "RemoteSha": "e2366ffd3196bf72b10730e50d3b45159c7621e3",
      "Hash": "8feb2a5866fc3af3cc6ac08caa32f38d"
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb5996d0bd962d214a11140d77589917"
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fbd35cac6ae7554d0e4f440bca1adf3a"
    },
    "rhdf5": {
      "Package": "rhdf5",
      "Version": "2.34.0",
      "Source": "Bioconductor",
      "Hash": "bf25b880f72c8b6dcbd8719b5ac9113b"
    },
    "rhdf5filters": {
      "Package": "rhdf5filters",
      "Version": "1.2.1",
      "Source": "Bioconductor",
      "Hash": "4e9258b05bbcbc1093eda53aa8051264"
    },
    "rlang": {
      "Package": "rlang",
      "Version": "0.4.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "599df23c40a4fce9c7b4764f28c37857"
    },
    "rpart": {
      "Package": "rpart",
      "Version": "4.1-15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9787c1fcb680e655d062e7611cadf78e"
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "249d8cd1e74a8f6a26194a91b47f21d1"
    },
    "rstudioapi": {
      "Package": "rstudioapi",
      "Version": "0.13",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "06c85365a03fdaf699966cc1d3cf53ea"
    },
    "rsvd": {
      "Package": "rsvd",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3a6b30449282b6a4b19ce267142c3299"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3ef1adfe46b7b144b970d74ce33ab0d6"
    },
    "scDblFinder": {
      "Package": "scDblFinder",
      "Version": "1.5.18",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "scDblFinder",
      "RemoteUsername": "plger",
      "RemoteRef": "HEAD",
      "RemoteSha": "01f4129adc2d8247bc1c36156bee50e8e4fdfa4c",
      "Hash": "d03d0512bc88d39c60e67d9a95669961"
    },
    "scales": {
      "Package": "scales",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6f76f71042411426ec8df6c54f34e6dd"
    },
    "scater": {
      "Package": "scater",
      "Version": "1.18.6",
      "Source": "Bioconductor",
      "Hash": "522082c4db93621132cbafb1a37b6df4"
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "373eb417aadd7c7f35861953f3fe3deb"
    },
    "scran": {
      "Package": "scran",
      "Version": "1.18.7",
      "Source": "Bioconductor",
      "Hash": "c327f8414fc0937c89b928174cabe46c"
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f6423b883393222fb5c022799374ccec"
    },
    "scuttle": {
      "Package": "scuttle",
      "Version": "1.0.4",
      "Source": "Bioconductor",
      "Hash": "82d75cd0746bda36735f10a0087e171c"
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6e3b6ae7fe02b5859e4bb277f218b8ae"
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f9ba299f2385e686745b066c6d7a7c4"
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "11b822ad6214111a4188d5e5fd1b144c"
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "947e4e02a79effa5d512473e10f41797"
    },
    "sparseMatrixStats": {
      "Package": "sparseMatrixStats",
      "Version": "1.2.1",
      "Source": "Bioconductor",
      "Hash": "1841edbaa151c369bd671a1b61bad097"
    },
    "spatstat.core": {
      "Package": "spatstat.core",
      "Version": "2.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ebfee0fecee2ce2ed37ceed011407b0c"
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4e8002e034d7d0af852b2bbcce851c2e"
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "2.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f04116a54dd6bedc16483625d2f21803"
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "2.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "615efff0d33e612b15dc3fc3ba0cc554"
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "72200a58cae0d7046e416e6be6d9d322"
    },
    "statmod": {
      "Package": "statmod",
      "Version": "1.4.35",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "53c27113461e8abbe2dc7125e22b2a39"
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9df5e6f9a7fa11b84adf0429961de66a"
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0759e6b6c0957edb1311028a49a35e76"
    },
    "survival": {
      "Package": "survival",
      "Version": "3.2-10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6b7453cd9bb32b12577c78d54eeea56a"
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b227d13e29222b4574486cfcbde077fa"
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090"
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "495e0434d9305716b6a87031570ce109"
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9c6c10e594f32096ede0c7d373ccbddd"
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c40b2d5824d829190f4b825f4496dfae"
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6ea435c354e8448819627cf686f66e0a"
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4a5081acfb7b81a572e4384a7aaf2af1"
    },
    "uuid": {
      "Package": "uuid",
      "Version": "0.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e4169eb989a5d03ccb6b628cad1b1b50"
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.1.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a9737c75f5f949695617b05e78281b2f"
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5cf1957f93076c19fdc81d01409d240b"
    },
    "vipor": {
      "Package": "vipor",
      "Version": "0.4.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ea85683da7f2bfa63a98dc6416892591"
    },
    "viridis": {
      "Package": "viridis",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6f6b49e5b3b5ee5a6d0c28bf1b4b9eb3"
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ce4f6271baa94776db692f1cb2055bee"
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "29df52c781e572c967f90de9713423c4"
    },
    "withr": {
      "Package": "withr",
      "Version": "2.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "caf4781c674ffa549a4676d2d77b13cc"
    },
    "xgboost": {
      "Package": "xgboost",
      "Version": "1.3.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7d622a45587a71dbea63bc161d054e3a"
    },
    "xml2": {
      "Package": "xml2",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d4d71a75dd3ea9eb5fa28cc21f9585e2"
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2"
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2826c5d9efb0a88f657c7a679c7106db"
    },
    "zeallot": {
      "Package": "zeallot",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ee9b643aa8331c45d8d82eb3a137c9bc"
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.36.0",
      "Source": "Bioconductor",
      "Hash": "effcbe90f6986ca6f81ce4d67db7238b"
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c2ea03282caa1f6972dc84fc5bf671cc"
    }
  }
}
