{
  "R": {
    "Version": "4.4.0",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.19/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.19/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.19/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.19/workflows"
      },
      {
        "Name": "BioCbooks",
        "URL": "https://bioconductor.org/packages/3.19/books"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.84.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a8235afbcd6316e6e91433ea47661013"
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.64.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "utils"
      ],
      "Hash": "9bc4cabd3bfda461409172213d932813"
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ef32d07aafdd12f24c5827374ae3590d"
    },
    "BiocIO": {
      "Package": "BiocIO",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "S4Vectors",
        "methods",
        "tools"
      ],
      "Hash": "f97a7ef01d364cf20d1946d43a3d526f"
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "47e968dfe563c1b22c2e20a067ec21d5"
    },
    "BiocNeighbors": {
      "Package": "BiocNeighbors",
      "Version": "1.22.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "RcppHNSW",
        "S4Vectors",
        "methods",
        "stats"
      ],
      "Hash": "da9f332c88453734623406dcca13ee03"
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "R",
        "codetools",
        "cpp11",
        "futile.logger",
        "methods",
        "parallel",
        "snow",
        "stats",
        "utils"
      ],
      "Hash": "7b6e79f86e3d1c23f62c5e2052e848d4"
    },
    "BiocSingular": {
      "Package": "BiocSingular",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "ScaledMatrix",
        "beachmat",
        "irlba",
        "methods",
        "rsvd",
        "utils"
      ],
      "Hash": "9d2e9fbd803f4eddfeb307b1ee376aad"
    },
    "BiocVersion": {
      "Package": "BiocVersion",
      "Version": "3.19.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "b892e27fc9659a4c8f8787d34c37b8b2"
    },
    "Biostrings": {
      "Package": "Biostrings",
      "Version": "2.72.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "crayon",
        "grDevices",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "48618c7c7b90b503837824ebcfee6363"
    },
    "Cairo": {
      "Package": "Cairo",
      "Version": "1.6-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "3918e6b40d27984ca4a99c73b92406c3"
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.30.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "SparseArray",
        "methods",
        "stats",
        "stats4"
      ],
      "Hash": "395472c65cd9d606a1a345687102f299"
    },
    "DelayedMatrixStats": {
      "Package": "DelayedMatrixStats",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors",
        "methods",
        "sparseMatrixStats"
      ],
      "Hash": "5d9536664ccddb0eaa68a90afe4ee76e"
    },
    "DropletUtils": {
      "Package": "DropletUtils",
      "Version": "1.24.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "HDF5Array",
        "IRanges",
        "Matrix",
        "R.utils",
        "Rcpp",
        "Rhdf5lib",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "dqrng",
        "edgeR",
        "methods",
        "rhdf5",
        "scuttle",
        "stats",
        "utils"
      ],
      "Hash": "77f762ad74d48a0ef578fc81deded039"
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "eaabdc7938aa3632a28273f53a0d226d"
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.40.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDbData",
        "IRanges",
        "R",
        "S4Vectors",
        "UCSC.utils",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "614124bc9fb80d222cfa0d2e3e76c339"
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.12",
      "Source": "Bioconductor",
      "Requirements": [
        "R"
      ],
      "Hash": "c3c792a7b7f2677be56e8632c5b7543d"
    },
    "GenomicAlignments": {
      "Package": "GenomicAlignments",
      "Version": "1.40.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rsamtools",
        "S4Vectors",
        "SummarizedExperiment",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "e539709764587c581b31e446dc84d7b8"
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.56.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "0fab423e3f49e207681eb404d9182a1e"
    },
    "HDF5Array": {
      "Package": "HDF5Array",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "IRanges",
        "Matrix",
        "R",
        "Rhdf5lib",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "rhdf5",
        "rhdf5filters",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "b10ddb24baf506cf7b4bc868ae65b984"
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "S4Vectors",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "836770692f7c8401090519228b93af32"
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-20",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "8dcfa99b14c296bc9f1fd64d52fd3ce7"
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-60",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "a56a6365b3fa73293ea8d084be0d9bb0"
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.6-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "8c7115cd3a0e048bda2a7cd110549f7a"
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "matrixStats",
        "methods"
      ],
      "Hash": "152dbbcde6a9a7c7f3beef79b68cd76a"
    },
    "R.methodsS3": {
      "Package": "R.methodsS3",
      "Version": "1.8.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "278c286fd6e9e75d0c2e8f731ea445c8"
    },
    "R.oo": {
      "Package": "R.oo",
      "Version": "1.26.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "methods",
        "utils"
      ],
      "Hash": "4fed809e53ddb5407b3da3d0f572e591"
    },
    "R.utils": {
      "Package": "R.utils",
      "Version": "2.12.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "R.oo",
        "methods",
        "tools",
        "utils"
      ],
      "Hash": "3dc2829b790254bfba21e60965787651"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "470851b6d5d0ac559e9d01bb352b4021"
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7"
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "45f0398006e83a5b10b72a90663d8d8c"
    },
    "RCurl": {
      "Package": "RCurl",
      "Version": "1.98-1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bitops",
        "methods"
      ],
      "Hash": "47f648d288079d0c696804ad4e55197e"
    },
    "RJSONIO": {
      "Package": "RJSONIO",
      "Version": "1.3-1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods"
      ],
      "Hash": "0c7658433758cea5bcae50edd02b55b7"
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "gplots",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "cc151930e20e16427bc3d0daec62b4a9"
    },
    "RSpectra": {
      "Package": "RSpectra",
      "Version": "0.16-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen"
      ],
      "Hash": "6b5ab997fd5ff6d46a5f1d9f8b76961c"
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "utils"
      ],
      "Hash": "5ea2700d21e038ace58269ecdbeb9ec0"
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.22",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods"
      ],
      "Hash": "f6baa1e06fb6c3724f601a764266cb0d"
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.12.8.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "e78bbbb81a5dcd71a4bd3268d6ede0b1"
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.4.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "stats",
        "utils"
      ],
      "Hash": "df49e3306f232ec28f1604e36a202847"
    },
    "RcppHNSW": {
      "Package": "RcppHNSW",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "methods"
      ],
      "Hash": "1f2dc32c27746a35196aaf95adb357be"
    },
    "RcppML": {
      "Package": "RcppML",
      "Version": "0.3.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "Rcpp",
        "RcppEigen",
        "methods",
        "stats"
      ],
      "Hash": "225157373f361daf85198a8d1ddaa733"
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5"
    },
    "RcppTOML": {
      "Package": "RcppTOML",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "f8a578aa91321ecec1292f1e2ffadeda"
    },
    "ResidualMatrix": {
      "Package": "ResidualMatrix",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "26b5d104b2d27d7aa3725c4e3aa1b3b9"
    },
    "Rhdf5lib": {
      "Package": "Rhdf5lib",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "c92ba8b9a2c5c9ff600a1062a3b7b727"
    },
    "RhpcBLASctl": {
      "Package": "RhpcBLASctl",
      "Version": "0.23-42",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c966ea2957ff75e77afa5c908dfc89e1"
    },
    "Rhtslib": {
      "Package": "Rhtslib",
      "Version": "3.0.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "tools",
        "zlibbioc"
      ],
      "Hash": "5d6514cd44a0106581e3310f3972a82e"
    },
    "Rsamtools": {
      "Package": "Rsamtools",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rhtslib",
        "S4Vectors",
        "XVector",
        "bitops",
        "methods",
        "stats",
        "utils",
        "zlibbioc"
      ],
      "Hash": "9762f24dcbdbd1626173c516bb64792c"
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "stats"
      ],
      "Hash": "f81f7764a3c3e310b1d40e1a8acee19e"
    },
    "S4Arrays": {
      "Package": "S4Arrays",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "R",
        "S4Vectors",
        "abind",
        "crayon",
        "methods",
        "stats"
      ],
      "Hash": "665d1f150ce8a6e7614375eafdbad645"
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.42.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "245ac721ca6088200392ea5251db9e3c"
    },
    "ScaledMatrix": {
      "Package": "ScaledMatrix",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "bac1c808a92d9c3f45d05e7a8c1b74f0"
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "4.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "MASS",
        "Matrix",
        "R",
        "RANN",
        "RColorBrewer",
        "ROCR",
        "Rcpp",
        "RcppAnnoy",
        "RcppEigen",
        "RcppProgress",
        "Rtsne",
        "SeuratObject",
        "cluster",
        "cowplot",
        "fitdistrplus",
        "future",
        "future.apply",
        "ggplot2",
        "ggrepel",
        "ggridges",
        "grDevices",
        "graphics",
        "grid",
        "httr",
        "ica",
        "igraph",
        "irlba",
        "jsonlite",
        "leiden",
        "lmtest",
        "matrixStats",
        "methods",
        "miniUI",
        "patchwork",
        "pbapply",
        "plotly",
        "png",
        "reticulate",
        "rlang",
        "scales",
        "scattermore",
        "sctransform",
        "shiny",
        "spatstat.core",
        "spatstat.geom",
        "stats",
        "tibble",
        "tools",
        "utils",
        "uwot"
      ],
      "Hash": "0d7350ea71e070760974a50692596c4d"
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "5.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen",
        "future",
        "future.apply",
        "generics",
        "grDevices",
        "grid",
        "lifecycle",
        "methods",
        "progressr",
        "rlang",
        "sp",
        "spam",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "e9b70412b7e04571b46101f5dcbaacad"
    },
    "SeuratWrappers": {
      "Package": "SeuratWrappers",
      "Version": "0.3.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteUsername": "satijalab",
      "RemoteRepo": "seurat-wrappers",
      "RemoteRef": "HEAD",
      "RemoteSha": "4da4c281cd9e3df8731466258608d354344ee262",
      "RemoteHost": "api.github.com",
      "Remotes": "welch-lab/liger, hms-dbmi/conos, immunogenomics/harmony, immunogenomics/presto, satijalab/seurat-data, velocyto-team/velocyto.R, SaskiaFreytag/schex@031320d, cole-trapnell-lab/monocle3, mojaveazure/seurat-disk, powellgenomicslab/Nebulosa, atakanekiz/CIPR-Package",
      "Requirements": [
        "BiocManager",
        "Matrix",
        "R",
        "Seurat",
        "cowplot",
        "ggplot2",
        "igraph",
        "methods",
        "remotes",
        "rlang",
        "rsvd",
        "stats",
        "utils"
      ],
      "Hash": "605fb08675f955e4c466e86102a5c632"
    },
    "SingleCellExperiment": {
      "Package": "SingleCellExperiment",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "GenomicRanges",
        "S4Vectors",
        "SummarizedExperiment",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "4476ad434a5e7887884521417cab3764"
    },
    "SparseArray": {
      "Package": "SparseArray",
      "Version": "1.4.3",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "XVector",
        "matrixStats",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "97e01fd020665f2b0c6bd182b0ab68c2"
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.34.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "2f6c8cc972ed6aee07c96e3dff729d15"
    },
    "UCSC.utils": {
      "Package": "UCSC.utils",
      "Version": "1.0.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "S4Vectors",
        "httr",
        "jsonlite",
        "methods",
        "stats"
      ],
      "Hash": "83d45b690bffd09d1980c224ef329f5b"
    },
    "XML": {
      "Package": "XML",
      "Version": "3.99-0.16.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "da3098169c887914551b607c66fe2a28"
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.44.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "R",
        "S4Vectors",
        "methods",
        "tools",
        "utils",
        "zlibbioc"
      ],
      "Hash": "4245b9938ac74c0dbddbebbec6036ab4"
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862"
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "cad6cf7f1d5f6e906700b9d3e718c796"
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "543776ae6848fde2f48ff3816d0628bc"
    },
    "batchelor": {
      "Package": "batchelor",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "ResidualMatrix",
        "S4Vectors",
        "ScaledMatrix",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "igraph",
        "methods",
        "scuttle",
        "stats",
        "utils"
      ],
      "Hash": "ec5dcf85cdf644b078d02deaf27a3bfd"
    },
    "beachmat": {
      "Package": "beachmat",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "SparseArray",
        "methods"
      ],
      "Hash": "10e94b1bce9070632a40c6b873f8b2d4"
    },
    "beeswarm": {
      "Package": "beeswarm",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "0f4e9d8caa6feaa7e409ae6c30f2ca66"
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d8d8ee39869c18d8846a184dd8a1af"
    },
    "bluster": {
      "Package": "bluster",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocNeighbors",
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "cluster",
        "igraph",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ed9597168d850071aa9abbbef7be7204"
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "976cf154dfb043c012d87cddd8bca363"
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "base64enc",
        "cachem",
        "grDevices",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "memoise",
        "mime",
        "rlang",
        "sass"
      ],
      "Hash": "a7fbf03946ad741129dc81098722fca1"
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bitops"
      ],
      "Hash": "34d90fa5845004236b9eacafc51d07b2"
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "fastmap",
        "rlang"
      ],
      "Hash": "5346f76a33eb7417812c270b04a5581b"
    },
    "callr": {
      "Package": "callr",
      "Version": "3.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "processx",
        "utils"
      ],
      "Hash": "d7e13f49c19103ece9e58ad2d83a7354"
    },
    "cli": {
      "Package": "cli",
      "Version": "3.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "1216ac65ac55ec0058a6f75d7ca0fd52"
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "0aaa05204035dc43ea0004b9c76611dd"
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c089a619a7fae175d149d89164f8c7d8"
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "f20c47fd52fae58b4e377c37bb8c335b"
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f22be39ec1d141fd03683c06f3a6e67"
    },
    "covr": {
      "Package": "covr",
      "Version": "3.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "crayon",
        "digest",
        "httr",
        "jsonlite",
        "methods",
        "rex",
        "stats",
        "utils",
        "withr",
        "yaml"
      ],
      "Hash": "a861cee34fbb4b107a73dd414ef56724"
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grDevices",
        "grid",
        "gtable",
        "methods",
        "rlang",
        "scales"
      ],
      "Hash": "b418e8423699d11c7f2087c2bfd07da2"
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5a295d7d963cc5035284dcdbaf334f4e"
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "methods",
        "utils"
      ],
      "Hash": "e8a1e41acf02548751f45c718d55aa6a"
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "htmltools",
        "jsonlite",
        "lazyeval"
      ],
      "Hash": "2b06f9e415a62b6762e4b8098d2aecbc"
    },
    "curl": {
      "Package": "curl",
      "Version": "5.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "411ca2c03b1ce5f548345d2fc2685f7a"
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.15.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "8ee9ac56ef633d0c7cab8b2ca87d683e"
    },
    "deldir": {
      "Package": "deldir",
      "Version": "2.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "24754fce82729ff85317dd195b6646a8"
    },
    "desc": {
      "Package": "desc",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "utils"
      ],
      "Hash": "99b79fcbd6c4d1ce087f5c5c758b384f"
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "crayon",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "feb5b7455eba422a2c110bb89852e6a3"
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.35",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "698ece7ba5a4fa4559e3d537e7ec3d31"
    },
    "dotCall64": {
      "Package": "dotCall64",
      "Version": "1.1-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "80f374ef8500fcdc5d84a0345b837227"
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "ellipsis",
        "generics",
        "glue",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "rlang",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "36f1ae62f026c8ba9f9b5c9a08c03297"
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "BH",
        "R",
        "Rcpp",
        "sitmo"
      ],
      "Hash": "824df2aeba88d701df5e79018b35b815"
    },
    "edgeR": {
      "Package": "edgeR",
      "Version": "4.2.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rcpp",
        "graphics",
        "limma",
        "locfit",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "20783ecb7e7cea3f351e8b21153e3eb8"
    },
    "ellipsis": {
      "Package": "ellipsis",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "rlang"
      ],
      "Hash": "bb0eec2fe32e88d9e2836c2f73ea2077"
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.22",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "66f39c7a21e03c4dcb2c2d21d738d603"
    },
    "fansi": {
      "Package": "fansi",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "utils"
      ],
      "Hash": "962174cf2aeb5b9eea581522286a911f"
    },
    "farver": {
      "Package": "farver",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "680887028577f3fa2a81e410ed0d6e42"
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77bd60a6157420d4ffa93b27cf6a58b8"
    },
    "filelock": {
      "Package": "filelock",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "192053c276525c8495ccfd523aa8f2d1"
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "grDevices",
        "methods",
        "stats",
        "survival"
      ],
      "Hash": "df82a154b37aad59c6a9cc2b54614296"
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "63cb26d12517c7863f5abb006c5e0f25"
    },
    "fs": {
      "Package": "fs",
      "Version": "1.6.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15aeb8c27f5ea5161f9f6a641fafd93a"
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "futile.options",
        "lambda.r",
        "utils"
      ],
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e"
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b"
    },
    "future": {
      "Package": "future",
      "Version": "1.33.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "digest",
        "globals",
        "listenv",
        "parallel",
        "parallelly",
        "utils"
      ],
      "Hash": "fd7b1d69d16d0d114e4fa82db68f184c"
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.11.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "future",
        "globals",
        "parallel",
        "utils"
      ],
      "Hash": "afe1507511629f44572e6c53b9baeb7c"
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15e9634c0fcd294799e9b2e929ed1b86"
    },
    "ggbeeswarm": {
      "Package": "ggbeeswarm",
      "Version": "0.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "beeswarm",
        "cli",
        "ggplot2",
        "lifecycle",
        "vipor"
      ],
      "Hash": "899f28fe0388b7f687d7453429c2474d"
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "cli",
        "glue",
        "grDevices",
        "grid",
        "gtable",
        "isoband",
        "lifecycle",
        "mgcv",
        "rlang",
        "scales",
        "stats",
        "tibble",
        "vctrs",
        "withr"
      ],
      "Hash": "44c6a2f8202d5b7e878ea274b1092426"
    },
    "ggrastr": {
      "Package": "ggrastr",
      "Version": "1.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Cairo",
        "R",
        "ggbeeswarm",
        "ggplot2",
        "grid",
        "png",
        "ragg"
      ],
      "Hash": "7c8178842114bfcd44e688e7fd84c52a"
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "ggplot2",
        "grid",
        "rlang",
        "scales",
        "withr"
      ],
      "Hash": "cc3361e234c4a5050e29697d675764aa"
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grid",
        "plyr",
        "scales",
        "withr"
      ],
      "Hash": "9d028e8f37c84dba356ce3c367a1978e"
    },
    "globals": {
      "Package": "globals",
      "Version": "0.16.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "codetools"
      ],
      "Hash": "2580567908cafd4f187c1e5a91e98b7f"
    },
    "glue": {
      "Package": "glue",
      "Version": "1.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "e0b3a53876554bd45879e596cdb10a52"
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "dbe0201f91eeb15918dd3fbf01ee689a"
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "R",
        "caTools",
        "gtools",
        "stats"
      ],
      "Hash": "e65e5d5dea4cbb9ba822dcd782b2ee1f"
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "utils"
      ],
      "Hash": "7d7f283939f563670a697165b2cf5560"
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "grid",
        "lifecycle",
        "rlang"
      ],
      "Hash": "e18861963cbc65a27736e02b3cd3c4a0"
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.9.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "2ace6c4a06297d0b364e0444384a2b82"
    },
    "harmony": {
      "Package": "harmony",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "RcppProgress",
        "RhpcBLASctl",
        "cowplot",
        "dplyr",
        "ggplot2",
        "methods",
        "rlang",
        "tibble"
      ],
      "Hash": "4f3b181961712ff4127a8634c1367f89"
    },
    "here": {
      "Package": "here",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "rprojroot"
      ],
      "Hash": "24b224366f9c2e7534d2344d10d59211"
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "base64enc",
        "digest",
        "ellipsis",
        "fastmap",
        "grDevices",
        "rlang",
        "utils"
      ],
      "Hash": "9d27e99cc90bd701c0a7a63e5923f9b7"
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "htmltools",
        "jsonlite",
        "yaml"
      ],
      "Hash": "6fdaa86d0700f8b3e92ee3c445a5a10d"
    },
    "httptest": {
      "Package": "httptest",
      "Version": "4.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "curl",
        "digest",
        "httr",
        "jsonlite",
        "stats",
        "testthat",
        "utils"
      ],
      "Hash": "cd910dc78e8edbc40b9723824baa7097"
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.6.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "Rcpp",
        "later",
        "promises",
        "utils"
      ],
      "Hash": "d55aa087c47a63ead0f6fc10f8fa1ee0"
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "curl",
        "jsonlite",
        "mime",
        "openssl"
      ],
      "Hash": "ac107251d9d9fd72f0ca8049988f1d7f"
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ba9b882bb834ecbdad37338a11f3f8"
    },
    "ids": {
      "Package": "ids",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "openssl",
        "uuid"
      ],
      "Hash": "99df65cfef20e525ed38c3d2577f7190"
    },
    "igraph": {
      "Package": "igraph",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "cli",
        "cpp11",
        "grDevices",
        "graphics",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgconfig",
        "rlang",
        "stats",
        "utils",
        "vctrs"
      ],
      "Hash": "c3b7d801d722e26e4cd888e042bf9af5"
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "methods",
        "stats"
      ],
      "Hash": "acb06a47b732c6251afd16e19c3201ff"
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grid",
        "utils"
      ],
      "Hash": "0080607b4a1a7b28979aecef976d8bc2"
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools"
      ],
      "Hash": "5aab57a3bd297eee1c1d862735972182"
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.8.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods"
      ],
      "Hash": "e1b9c55281c5adc4dd113652d9e26768"
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "graphics",
        "stats"
      ],
      "Hash": "b64ec208ac5bc1852b285f665d6368b3"
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "formatR"
      ],
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad"
    },
    "later": {
      "Package": "later",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "rlang"
      ],
      "Hash": "a3e051d405326b8b0012377434c62b37"
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.22-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "stats",
        "utils"
      ],
      "Hash": "7c5e89f04e72d6611c77451f6331a091"
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370"
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "igraph",
        "methods",
        "reticulate"
      ],
      "Hash": "355993b12fa6e5c9e4b1f9077adabfbd"
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "rlang"
      ],
      "Hash": "b8552d117e1b808b09a832f589b79035"
    },
    "limma": {
      "Package": "limma",
      "Version": "3.60.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "statmod",
        "stats",
        "utils"
      ],
      "Hash": "eb9369d11da98acc7f7ca4cdab0ee3d8"
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "e2fca3e12e4db979dccc6e519b10a7ee"
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-40",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats",
        "zoo"
      ],
      "Hash": "c6fafa6cccb1e1dfe7f7d122efd6e6a7"
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "lattice"
      ],
      "Hash": "3885127e04b35dafded049075057ad83"
    },
    "lpSolve": {
      "Package": "lpSolve",
      "Version": "5.6.20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2801c8082e89ed84cc0dbe43de850d31"
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "7ce2733a9826b3aeb1775d56fd305472"
    },
    "maketools": {
      "Package": "maketools",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "1621cb95007b3e1626bb5597c5faf799"
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4b3ea27a19d669c0405b38134d89a9d1"
    },
    "memoise": {
      "Package": "memoise",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cachem",
        "rlang"
      ],
      "Hash": "e2817ccf4a065c5d9d7f2cfbe7c1d78c"
    },
    "metapod": {
      "Package": "metapod",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rcpp"
      ],
      "Hash": "026552a86c3aa0d92d4d8b12d80010cc"
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.9-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "nlme",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "110ee9d83b496279960e162ac97764ce"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tools"
      ],
      "Hash": "18e9c28c1d3ca1560ce30658b22ce104"
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "shiny",
        "utils"
      ],
      "Hash": "fec5f52652d60615fdb3957b3d74324a"
    },
    "mockery": {
      "Package": "mockery",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "testthat"
      ],
      "Hash": "c28ce5f7c2293d76b91657f3fe30c50b"
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "colorspace",
        "methods"
      ],
      "Hash": "4fd8900853b746af55b81fda99da7695"
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-163",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "8d1938040a05566f4f7a14af4feadd6b"
    },
    "openssl": {
      "Package": "openssl",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "askpass"
      ],
      "Hash": "ea2475b073243d9d338aa8f086ce973e"
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.37.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "parallel",
        "tools",
        "utils"
      ],
      "Hash": "5410df8d22bd36e616f2a2343dbb328c"
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "stats",
        "utils"
      ],
      "Hash": "c446b30cb33ec125ff02588b60660ccb"
    },
    "paws": {
      "Package": "paws",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.analytics",
        "paws.application.integration",
        "paws.compute",
        "paws.cost.management",
        "paws.customer.engagement",
        "paws.database",
        "paws.machine.learning",
        "paws.management",
        "paws.networking",
        "paws.security.identity",
        "paws.storage"
      ],
      "Hash": "cec12e707388b40a0109c6e89b866176"
    },
    "paws.analytics": {
      "Package": "paws.analytics",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "b27a7fab001c13d69cce406315f991c1"
    },
    "paws.application.integration": {
      "Package": "paws.application.integration",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "15be816c36116393eff157fe061cb564"
    },
    "paws.common": {
      "Package": "paws.common",
      "Version": "0.3.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "base64enc",
        "digest",
        "httr",
        "jsonlite",
        "methods",
        "utils",
        "xml2"
      ],
      "Hash": "7cc535da7013baf4951785ee2b9e41cc"
    },
    "paws.compute": {
      "Package": "paws.compute",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "421a8a6138b5707842d49c6b47cf48d8"
    },
    "paws.cost.management": {
      "Package": "paws.cost.management",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "37d8fd15437c3e41cbeaa826860b1452"
    },
    "paws.customer.engagement": {
      "Package": "paws.customer.engagement",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "b2f091502ec3a74caba2628bfbc5aba1"
    },
    "paws.database": {
      "Package": "paws.database",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "27c9d75627046976c89f4a43279b5078"
    },
    "paws.machine.learning": {
      "Package": "paws.machine.learning",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "27fbc04572e5a74200c75ebf7a1ca5b3"
    },
    "paws.management": {
      "Package": "paws.management",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "85b61065160322f6729269cb59bd434e"
    },
    "paws.networking": {
      "Package": "paws.networking",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "603472424ac4c5244abba09728bd15e5"
    },
    "paws.security.identity": {
      "Package": "paws.security.identity",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "d4d9f0ac7e665888c12d799421fcf345"
    },
    "paws.storage": {
      "Package": "paws.storage",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "paws.common"
      ],
      "Hash": "d0a0428696cdc8099e8c93d2257b21f2"
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "parallel"
      ],
      "Hash": "52f8028b028076bc3b7ee5d6251abf0d"
    },
    "pheatmap": {
      "Package": "pheatmap",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "scales",
        "stats"
      ],
      "Hash": "db1fb0021811b6693741325bbe916e58"
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.9.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cli",
        "fansi",
        "glue",
        "lifecycle",
        "rlang",
        "utf8",
        "utils",
        "vctrs"
      ],
      "Hash": "15da5a8412f317beeee6175fbc76f4bb"
    },
    "pkgbuild": {
      "Package": "pkgbuild",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "desc",
        "processx"
      ],
      "Hash": "a29e8e134a460a01e0ca67a4763c595b"
    },
    "pkgcache": {
      "Package": "pkgcache",
      "Version": "2.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "curl",
        "filelock",
        "jsonlite",
        "processx",
        "tools",
        "utils"
      ],
      "Hash": "dc112aecccbe85158de8e4f9531b4783"
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "01f28d4278f15c76cddbea05899c5d6f"
    },
    "pkgdepends": {
      "Package": "pkgdepends",
      "Version": "0.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "curl",
        "desc",
        "filelock",
        "jsonlite",
        "lpSolve",
        "pkgbuild",
        "pkgcache",
        "processx",
        "ps",
        "stats",
        "utils",
        "zip"
      ],
      "Hash": "015473b3c114c47a50282be0dbe80ad4"
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "crayon",
        "desc",
        "fs",
        "glue",
        "methods",
        "pkgbuild",
        "rlang",
        "rprojroot",
        "utils",
        "withr"
      ],
      "Hash": "876c618df5ae610be84356d5d7a5d124"
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.9.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "base64enc",
        "crosstalk",
        "data.table",
        "digest",
        "dplyr",
        "ggplot2",
        "htmltools",
        "htmlwidgets",
        "httr",
        "jsonlite",
        "lazyeval",
        "magrittr",
        "promises",
        "purrr",
        "rlang",
        "scales",
        "tibble",
        "tidyr",
        "tools",
        "vctrs",
        "viridisLite"
      ],
      "Hash": "af4b92cb3828aa30002e2f945c49c2d7"
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "ec0e5ab4e5f851f6ef32cd1d1984957f"
    },
    "png": {
      "Package": "png",
      "Version": "0.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "bd54ba8a0a5faded999a7aab6e46b374"
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "436542aadb70675e361cf359285af7c7"
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f"
    },
    "prettyunits": {
      "Package": "prettyunits",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "6b01fc98b1e86c4f705ce9dcfd2f57c7"
    },
    "processx": {
      "Package": "processx",
      "Version": "3.8.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "ps",
        "utils"
      ],
      "Hash": "0c90a7d71988856bad2a2a45dd871bb9"
    },
    "progressr": {
      "Package": "progressr",
      "Version": "0.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "digest",
        "utils"
      ],
      "Hash": "ac50c4ffa8f6a46580dd4d7813add3c4"
    },
    "promises": {
      "Package": "promises",
      "Version": "1.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "Rcpp",
        "later",
        "magrittr",
        "rlang",
        "stats"
      ],
      "Hash": "4ab2c43adb4d4699cf3690acd378d75d"
    },
    "ps": {
      "Package": "ps",
      "Version": "1.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "dd2b9319ee0656c8acf45c7f40c59de7"
    },
    "purrr": {
      "Package": "purrr",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "magrittr",
        "rlang"
      ],
      "Hash": "97def703420c8ab10d8f0e6c72101e02"
    },
    "ragg": {
      "Package": "ragg",
      "Version": "1.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "systemfonts",
        "textshaping"
      ],
      "Hash": "539dcb63ce611fe389b4c8e2b546cf24"
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d"
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tibble"
      ],
      "Hash": "76c9e04c712a05848ae7a23d2f170a40"
    },
    "remotes": {
      "Package": "remotes",
      "Version": "2.4.2",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "227045be9aee47e6dda9bb38ac870d67"
    },
    "renv": {
      "Package": "renv",
      "Version": "1.0.7",
      "OS_type": null,
      "NeedsCompilation": "no",
      "Repository": "CRAN",
      "Source": "Repository"
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "plyr",
        "stringr"
      ],
      "Hash": "bb5996d0bd962d214a11140d77589917"
    },
    "restfulr": {
      "Package": "restfulr",
      "Version": "0.0.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RCurl",
        "S4Vectors",
        "XML",
        "methods",
        "rjson",
        "yaml"
      ],
      "Hash": "44651c1e68eda9d462610aca9f15a815"
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.26-9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "reticulate",
      "RemoteRef": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "RemoteSha": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppTOML",
        "graphics",
        "here",
        "jsonlite",
        "methods",
        "png",
        "rappdirs",
        "utils",
        "withr"
      ],
      "Hash": "1fbd16fb844017519cdede66bc95a5a2"
    },
    "rex": {
      "Package": "rex",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "lazyeval"
      ],
      "Hash": "093584b944440c5cd07a696b3c8e0e4c"
    },
    "rhdf5": {
      "Package": "rhdf5",
      "Version": "2.48.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rhdf5lib",
        "methods",
        "rhdf5filters"
      ],
      "Hash": "74d8c5aeb96d090ce8efc9ffd16afa2b"
    },
    "rhdf5filters": {
      "Package": "rhdf5filters",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rhdf5lib"
      ],
      "Hash": "99e15369f8fb17dc188377234de13fc6"
    },
    "rjson": {
      "Package": "rjson",
      "Version": "0.2.21",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "f9da75e6444e95a1baf8ca24909d63b9"
    },
    "rlang": {
      "Package": "rlang",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "42548638fae05fd9a9b5f3f437fbbbe2"
    },
    "rpart": {
      "Package": "rpart",
      "Version": "4.1.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats"
      ],
      "Hash": "b3d390424f41d04174cccf84d49676c2"
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4c8415e0ec1e29f3f4f6fc108bef0144"
    },
    "rsvd": {
      "Package": "rsvd",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R"
      ],
      "Hash": "b462187d887abc519894874486dbd6fd"
    },
    "rtracklayer": {
      "Package": "rtracklayer",
      "Version": "1.64.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocIO",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicAlignments",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rsamtools",
        "S4Vectors",
        "XML",
        "XVector",
        "curl",
        "httr",
        "methods",
        "restfulr",
        "tools",
        "zlibbioc"
      ],
      "Hash": "3d6f004fce582bd7d68e2e18d44abbc1"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.4.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "fs",
        "htmltools",
        "rappdirs",
        "rlang"
      ],
      "Hash": "d53dbfddf695303ea4ad66f86e99b95d"
    },
    "scDblFinder": {
      "Package": "scDblFinder",
      "Version": "1.13.5",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "plger",
      "RemoteRepo": "scDblFinder",
      "RemoteRef": "master",
      "RemoteSha": "30bf4ada2471bd77637ad312d8e9aff1db3e55dd",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "MASS",
        "Matrix",
        "R",
        "Rsamtools",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "bluster",
        "igraph",
        "methods",
        "rtracklayer",
        "scater",
        "scran",
        "scuttle",
        "stats",
        "utils",
        "xgboost"
      ],
      "Hash": "ea01d53534b63423e57ec7a5b1f2a5df"
    },
    "scales": {
      "Package": "scales",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "RColorBrewer",
        "cli",
        "farver",
        "glue",
        "labeling",
        "lifecycle",
        "munsell",
        "rlang",
        "viridisLite"
      ],
      "Hash": "c19df082ba346b0ffa6f833e92de34d1"
    },
    "scater": {
      "Package": "scater",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "Matrix",
        "MatrixGenerics",
        "RColorBrewer",
        "RcppML",
        "Rtsne",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "ggbeeswarm",
        "ggplot2",
        "ggrastr",
        "ggrepel",
        "methods",
        "pheatmap",
        "rlang",
        "scuttle",
        "stats",
        "utils",
        "uwot",
        "viridis"
      ],
      "Hash": "4a6eb8ab8a2b926fe67cf83aa731a3df"
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "scales"
      ],
      "Hash": "373eb417aadd7c7f35861953f3fe3deb"
    },
    "scran": {
      "Package": "scran",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "BiocGenerics",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "bluster",
        "dqrng",
        "edgeR",
        "igraph",
        "limma",
        "metapod",
        "methods",
        "scuttle",
        "statmod",
        "stats",
        "utils"
      ],
      "Hash": "5b11173a6b49f06dda0db31e80caa561"
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "dplyr",
        "future",
        "future.apply",
        "ggplot2",
        "gridExtra",
        "magrittr",
        "matrixStats",
        "methods",
        "reshape2",
        "rlang"
      ],
      "Hash": "85ff27d18c45a92993f6d7fd09c41f79"
    },
    "scuttle": {
      "Package": "scuttle",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "6d94b72071aefd6e8b041c34ee83ebd0"
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "bslib",
        "cachem",
        "commonmark",
        "crayon",
        "digest",
        "ellipsis",
        "fastmap",
        "glue",
        "grDevices",
        "htmltools",
        "httpuv",
        "jsonlite",
        "later",
        "lifecycle",
        "methods",
        "mime",
        "promises",
        "rlang",
        "sourcetools",
        "tools",
        "utils",
        "withr",
        "xtable"
      ],
      "Hash": "6e3b6ae7fe02b5859e4bb277f218b8ae"
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "c956d93f6768a9789edbc13072b70c78"
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "40b74690debd20c57d93d8c246b305d4"
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "947e4e02a79effa5d512473e10f41797"
    },
    "sp": {
      "Package": "sp",
      "Version": "2.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "75940133cca2e339afce15a586f85b11"
    },
    "spam": {
      "Package": "spam",
      "Version": "2.10-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "dotCall64",
        "grid",
        "methods"
      ],
      "Hash": "ffe1f9e95a4375530747b268f82b5086"
    },
    "sparseMatrixStats": {
      "Package": "sparseMatrixStats",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Matrix",
        "MatrixGenerics",
        "Rcpp",
        "matrixStats",
        "methods"
      ],
      "Hash": "7e500a5a527460ca0406473bdcade286"
    },
    "spatstat.core": {
      "Package": "spatstat.core",
      "Version": "2.4-4",
      "Source": "URL",
      "Repository": "CRAN",
      "RemoteType": "url",
      "RemoteUrl": "https://cran.r-project.org/src/contrib/Archive/spatstat.core/spatstat.core_2.4-4.tar.gz",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "goftest",
        "grDevices",
        "graphics",
        "methods",
        "mgcv",
        "nlme",
        "rpart",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.random",
        "spatstat.sparse",
        "spatstat.utils",
        "stats",
        "tensor",
        "utils"
      ],
      "Hash": "2f7ef6ee31ead12a5ee4996f91051477"
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "spatstat.utils"
      ],
      "Hash": "114a35341cb4955e1b8d30e28ec356c6"
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "3.2-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "deldir",
        "grDevices",
        "graphics",
        "methods",
        "polyclip",
        "spatstat.data",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "96b9f23da42d16660aa6d136ad99cf5f"
    },
    "spatstat.random": {
      "Package": "spatstat.random",
      "Version": "3.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "methods",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "01aff260c49550e820a47d97e566af6a"
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "3.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "methods",
        "spatstat.utils",
        "stats",
        "tensor",
        "utils"
      ],
      "Hash": "1daaecefd754bb259a5ad5ce95a2cdcc"
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "81d929f43f8532c1f8180a105449d414"
    },
    "statmod": {
      "Package": "statmod",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "26e158d12052c279bdd4ba858b80fb1f"
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "bba431031d30789535745a9627ac9271"
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "glue",
        "magrittr",
        "stringi"
      ],
      "Hash": "0759e6b6c0957edb1311028a49a35e76"
    },
    "survival": {
      "Package": "survival",
      "Version": "3.5-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "184d7799bca4ba8c3be72ea396f4b9a3"
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3a1be13d68d47a8cd0bfd74739ca1555"
    },
    "systemfonts": {
      "Package": "systemfonts",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11"
      ],
      "Hash": "6d538cff441f0f1f36db2209ac7495ac"
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090"
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "brio",
        "callr",
        "cli",
        "desc",
        "digest",
        "ellipsis",
        "evaluate",
        "jsonlite",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgload",
        "praise",
        "processx",
        "ps",
        "rlang",
        "utils",
        "waldo",
        "withr"
      ],
      "Hash": "877508719fcb8c9525eccdadf07a5102"
    },
    "textshaping": {
      "Package": "textshaping",
      "Version": "0.3.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "systemfonts"
      ],
      "Hash": "997aac9ad649e0ef3b97f96cddd5622b"
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "fansi",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "pkgconfig",
        "rlang",
        "utils",
        "vctrs"
      ],
      "Hash": "a84e2cc86d07289b3b6f5069df7a004c"
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "dplyr",
        "ellipsis",
        "glue",
        "lifecycle",
        "magrittr",
        "purrr",
        "rlang",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "450d7dfaedde58e28586b854eeece4fa"
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ellipsis",
        "glue",
        "purrr",
        "rlang",
        "vctrs"
      ],
      "Hash": "7243004a708d06d4716717fa1ff5b2fe"
    },
    "tryCatchLog": {
      "Package": "tryCatchLog",
      "Version": "1.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "ee3a0717cd6a7a190bb32b90ccf0178b"
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "62b65c52671e6665f803ff02954446e9"
    },
    "uuid": {
      "Package": "uuid",
      "Version": "0.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "e4169eb989a5d03ccb6b628cad1b1b50"
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "FNN",
        "Matrix",
        "RSpectra",
        "Rcpp",
        "RcppAnnoy",
        "RcppProgress",
        "dqrng",
        "irlba",
        "methods"
      ],
      "Hash": "f693a0ca6d34b02eb432326388021805"
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "rlang"
      ],
      "Hash": "c03fa420630029418f7e6da3667aac4a"
    },
    "vipor": {
      "Package": "vipor",
      "Version": "0.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "86493c62c14eb78140f1725003958a77"
    },
    "viridis": {
      "Package": "viridis",
      "Version": "0.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "gridExtra",
        "viridisLite"
      ],
      "Hash": "acd96d9fa70adeea4a5a1150609b9745"
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c826c7c4241b6fc89ff55aaea3fa7491"
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cli",
        "diffobj",
        "fansi",
        "glue",
        "methods",
        "rematch2",
        "rlang",
        "tibble"
      ],
      "Hash": "2c993415154cdb94649d99ae138ff5e5"
    },
    "withr": {
      "Package": "withr",
      "Version": "3.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "d31b6c62c10dcf11ec530ca6b0dd5d35"
    },
    "xgboost": {
      "Package": "xgboost",
      "Version": "1.7.7.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "data.table",
        "jsonlite",
        "methods"
      ],
      "Hash": "6303e61eac62aef7bd2b396ef7e24386"
    },
    "xml2": {
      "Package": "xml2",
      "Version": "1.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "methods",
        "rlang"
      ],
      "Hash": "1d0336142f4cd25d8d23cd3ba7a8fb61"
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2"
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "29240487a071f535f5e5d5a323b7afbd"
    },
    "zeallot": {
      "Package": "zeallot",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ee9b643aa8331c45d8d82eb3a137c9bc"
    },
    "zip": {
      "Package": "zip",
      "Version": "2.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fcc4bd8e6da2d2011eb64a5e5cc685ab"
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Hash": "3db02e3c460e1c852365df117a2b441b"
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "035d1c7c12593038c26fb1c2fd40c4d2"
    }
  }
}
